all04: all04.cpp
	# clang++  -Xpreprocessor  -fopenmp  -I/usr/local/include -I/opt/homebrew/opt/libomp/include -L/usr/local/lib -L/opt/homebrew/opt/libomp/lib -lomp all04.cpp  -o all04
	# g++ -I/usr/local/include -I/opt/homebrew/opt/libomp/include -L/usr/local/lib -L/opt/homebrew/opt/libomp/lib -lomp all04.cpp -o all04
	g++ all04.cpp -o all04 -fopenmp

clean: 
	rm -rf all04